name: 'Setup and cache Flutter SDK'
author: 'Hrishikesh Kadam <hrkadam.92@gmail.com>'
description: 'Composite GitHub Action to setup and cache the Flutter SDK.'
inputs:
  ref:
    description: 'channel (stable, beta or master), version(2.8.0) or any git reference(2.8.0-3.3.pre).'
    required: false
    default: 'stable'
  setFlutterRootPath:
    description: 'Set FLUTTER_ROOT to path where Flutter is installed.'
    required: false
    default: 'false'
  setPubCachePath:
    description: 'Set PUB_CACHE to desired path, where pub saves dependencies.'
    required: false
    default: ''
  addPubCacheBinToPath:
    description: 'Add PUB_CACHE bin to PATH.\n
    Note: On Windows, activated global packages can be run by without specifying 
    `dart pub global run` only on pwsh, cmd and powershell.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Check Flutter ${{ inputs.ref }} HEAD
      run: |
        echo "FLUTTER_REF_HEAD=$(git ls-remote https://github.com/flutter/flutter ${{ inputs.ref }} | cut -f 1)" >> $GITHUB_ENV
      shell: bash

    - name: Check if Flutter is cached
      id: cache-flutter
      uses: actions/cache@v2
      with:
        path: ${{ runner.tool_cache }}/flutter
        key: flutter-${{ runner.os }}-${{ inputs.ref }}-${{ env.FLUTTER_REF_HEAD }}

    - name: Clone Flutter repository if not cached
      if: steps.cache-flutter.outputs.cache-hit != 'true'
      run: |
        git clone --branch ${{ inputs.ref }} --depth 1 \
        https://github.com/flutter/flutter $RUNNER_TOOL_CACHE/flutter
      shell: bash

    - name: Set FLUTTER_ROOT on Linux or macOS
      if: inputs.setFlutterRootPath == 'true' && runner.os != 'Windows'
      run: echo "FLUTTER_ROOT=$RUNNER_TOOL_CACHE/flutter" >> $GITHUB_ENV
      shell: bash

    - name: Set FLUTTER_ROOT on Windows
      if: inputs.setFlutterRootPath == 'true' && runner.os == 'Windows'
      run: echo "FLUTTER_ROOT=$env:RUNNER_TOOL_CACHE\flutter" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh

    - name: Add Flutter to PATH
      run: echo "$RUNNER_TOOL_CACHE/flutter/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set PUB_CACHE on Linux or macOS
      if: inputs.setPubCachePath != '' && runner.os != 'Windows'
      run: |
        PUB_CACHE=${{ inputs.setPubCachePath }}
        echo "PUB_CACHE=$PUB_CACHE" >> $GITHUB_ENV
      shell: bash

    - name: Set PUB_CACHE on Windows
      if: inputs.setPubCachePath != '' && runner.os == 'Windows'
      run: |
        $env:PUB_CACHE="${{ inputs.setPubCachePath }}"
        echo "PUB_CACHE=$env:PUB_CACHE" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh

    - name: Add PUB_CACHE bin to PATH
      if: inputs.addPubCacheBinToPath == 'true'
      run: $GITHUB_ACTION_PATH/src/add-pub-cache-bin-to-path.sh
      shell: bash

    - run: flutter --version
      shell: bash

branding:
  icon: 'heart'
  color: 'blue'
